
import React from 'react';

export const TRANSLATIONS = {
  en: {
    nav: { home: 'Premium Home', about: 'About', tools: 'Professional Hub', blog: 'Chronicles', contact: 'Support', admin: 'Access' },
    hero: { title: 'Discover Your Destiny with Astro Vision AI', subtitle: 'Advanced AI-powered astrology insights across 5 languages.' },
    contact: {
      title: 'Contact Celestial Support',
      subtitle: 'Reach Out',
      desc: 'Have questions about your reports or the planetary alignments? Our human guides are here to assist your journey.',
      nameLabel: 'Your Name',
      namePlaceholder: 'Full Name',
      emailLabel: 'Email Address',
      emailPlaceholder: 'email@address.com',
      messageLabel: 'How can we help?',
      messagePlaceholder: 'Describe your inquiry or celestial feedback...',
      button: 'Send Message',
      officeTitle: 'Global Presence',
      officeAddr: 'Office HQ',
      officeAddrDetail: '123 Astral Lane, Starry Heights, Mumbai, India',
      socialTitle: 'Follow Our Journey'
    },
    categories: {
      identity: 'Cosmic Identity',
      vedic: 'Vedic Wisdom',
      lifepath: 'Life & Purpose',
      connections: 'Synastry & Love',
      spiritual: 'Spirit & Soul',
      remedies: 'Remedies & Luck'
    },
    tools: {
      zodiac: 'Zodiac Sign Finder',
      moon: 'Moon Phase Tracker',
      numerology: 'Numerology Calculator',
      compatibility: 'Compatibility Checker',
      kundli: 'Basic Kundli Chart',
      lucky: 'Lucky Profile',
      daily: 'Daily Horoscope',
      mangal: 'Mangal Dosha Check',
      sadesati: 'Sade Sati Status',
      chinese: 'Chinese Zodiac',
      ascendant: 'Rising Sign (Ascendant)',
      career: 'Career Path Finder',
      finance: 'Wealth & Finance',
      health: 'Health & Vitality',
      relationship_karma: 'Relationship Karma',
      tarot: 'Daily Tarot Draw',
      aura: 'Aura Color Analysis',
      chakra: 'Chakra Alignment',
      pastlife: 'Past Life Regression',
      spiritanimal: 'Spirit Animal Connection',
      nakshatra: 'Nakshatra Finder',
      gemstone: 'Remedial Gemstones',
      ritual: 'Personalized Rituals',
      dasha: 'Planetary Dasha',
      ayurveda: 'Ayurvedic Dosha',
      travel: 'Travel Forecast',
      dream: 'Dream Interpreter',
      name_numerology: 'Name Vibrations',
      love_language: 'Love Language',
      shadow_self: 'Shadow Self Analysis',
      elements: 'Elemental Balance',
      vertex: 'Vertex Destiny Gate',
      fortune: 'Part of Fortune',
      ask_gemini: 'Ask Gemini (Free-form)',
      planetary_hours: 'Planetary Hours'
    },
    toolDescriptions: {
      zodiac: 'Decipher the fundamental blueprint of your ego, emotions, and outward persona.',
      moon: 'Track the lunar cycles to align your emotional rhythm with the celestial tides.',
      numerology: 'Calculate your Life Path number to uncover the vibrational frequency of your destiny.',
      compatibility: 'Synthesize two birth charts to evaluate the energetic harmony and karmic challenges of your union.',
      kundli: 'Generate a comprehensive Vedic snapshot of planetary positions at your exact moment of birth.',
      lucky: 'Identify your auspicious colors, numbers, and gemstones based on planetary strengths.',
      daily: 'Receive high-precision temporal forecasts for career, health, and interpersonal relationships.',
      mangal: 'Analyze Mars placement to identify energetic imbalances and suggest corrective remedies.',
      sadesati: 'Calculate the transit of Saturn relative to your natal Moon to understand current life tests.',
      chinese: 'Discover your animal sign and elemental affinity based on the Lunar calendar.',
      ascendant: 'Determine your Rising Sign to understand your physical vitality and immediate world-view.',
      career: 'Analyze the 10th House and Midheaven to identify your optimal vocational path.',
      finance: 'Evaluate planetary wealth indicators to optimize your material abundance and financial security.',
      health: 'Assess the 6th House and elemental balance to maintain physical and spiritual vitality.',
      relationship_karma: 'Examine past-life echoes and karmic patterns within your significant partnerships.',
      tarot: 'Draw a single card to receive symbolic guidance for the current 24-hour cycle.',
      aura: 'Visualize the electromagnetic field surrounding your physical body based on planetary transits.',
      chakra: 'Identify energy blockages and alignment opportunities through your cosmic signature.',
      pastlife: 'Access deep subconscious memories and soul-themes carried over from previous incarnations.',
      spiritanimal: 'Identify your celestial animal guide based on your primal energetic resonance.',
      nakshatra: 'Find your specific lunar mansion to uncover the subtle nuances of your character.',
      gemstone: 'Receive personalized recommendations for remedial stones to enhance planetary strengths.',
      ritual: 'Discover bespoke spiritual practices tailored to your current astrological transits.',
      dasha: 'Analyze the chronological sequence of planetary periods governing your life cycles.',
      ayurveda: 'Determine your Dosha (Vata, Pitta, Kapha) based on your natal elemental balance.',
      travel: 'Consult the stars to find the most auspicious times and directions for your journeys.',
      dream: 'Interpret the symbolic language of your subconscious through an oneiric-astrological lens.',
      name_numerology: 'Analyze the vibrational impact of your name on your life unfolding journey.',
      love_language: 'Discover your cosmic style of giving and receiving affection based on Venus and Mars.',
      shadow_self: 'Explore the hidden, repressed aspects of your personality for deeper self-integration.',
      elements: 'Calculate the distribution of Fire, Earth, Air, and Water within your natal blueprint.',
      vertex: 'Identify your destiny gate and fated encounters through this mathematical power point.',
      fortune: 'Locate the Part of Fortune to find where worldly success and joy naturally flow.',
      ask_gemini: 'Pose open-ended metaphysical questions to our master intelligence for deep synthesis.',
      planetary_hours: 'Calculate the governing planet for each hour to optimize your timing for specific actions.'
    },
    labels: {
      name: 'Full Name',
      pronouns: 'Pronouns',
      dob: 'Date of Birth',
      tob: 'Time of Birth',
      loc: 'Place of Birth',
      submit: 'Calculate Insights',
      loading: 'Aligning Stars...',
      partnerName: 'Partner Name',
      westernSign: 'Western Sun Sign',
      vedicSign: 'Vedic Rashi (Approx)',
      searchTools: 'Search 30+ specialized tools...',
      backToHub: 'Back to Hub',
      moduleCode: 'Module Code',
      inquiryDetails: 'Inquiry Details',
      systemStandby: 'System Standby',
      initializeDataDesc: 'Initialize birth coordinates to receive specific module feedback.',
      dayPlaceholder: 'DD',
      monthPlaceholder: 'MM',
      yearPlaceholder: 'YYYY',
      pronounOptions: ['He/Him', 'She/Her', 'They/Them', 'Prefer not to say']
    },
    results: {
      profile: 'Cosmic Profile',
      status: 'Status',
      phase: 'Phase',
      rising: 'Rising Sign',
      sun: 'Sun Sign',
      focus: 'Focus',
      forecast: 'Forecast',
      moonPhase: 'Moon Phase',
      in: 'in'
    }
  },
  te: {
    nav: { home: 'ప్రీమియం హోమ్', about: 'గురించి', tools: 'ప్రొఫెషనల్ హబ్', blog: 'క్రానికల్స్', contact: 'సంప్రదించండి', admin: 'అడ్మిన్' },
    hero: { title: 'ఆస్ట్రో విజన్ AI తో మీ విధిని కనుగొనండి', subtitle: '5 భాషలలో అధునాతన AI ఆధారిత జ్యోతిషశాస్త్ర అంతర్దృష్తులు.' },
    contact: {
      title: 'కాస్మిక్ సపోర్ట్‌ని సంప్రదించండి',
      subtitle: 'మమ్మల్ని సంప్రదించండి',
      desc: 'మీ రిపోర్ట్‌లు లేదా గ్రహాల స్థితి గురించి ఏవైనా ప్రశ్నలు ఉన్నాయా? మీకు సహాయం చేయడానికి మా గైడ్‌లు సిద్ధంగా ఉన్నారు.',
      nameLabel: 'మీ పేరు',
      namePlaceholder: 'పూర్తి పేరు',
      emailLabel: 'ఈమెయిల్ అడ్రస్',
      emailPlaceholder: 'email@address.com',
      messageLabel: 'మేము మీకు ఎలా సహాయపడగలము?',
      messagePlaceholder: 'మీ ప్రశ్నను వివరించండి...',
      button: 'సందేశం పంపండి',
      officeTitle: 'ప్రపంచవ్యాప్త ఉనికి',
      officeAddr: 'ముఖ్య కార్యాలయం',
      officeAddrDetail: '123 ఆస్ట్రల్ లేన్, స్టార్రీ హైట్స్, ముంబై, ఇండియా',
      socialTitle: 'మా ప్రయాణాన్ని అనుసరించండి'
    },
    categories: {
      identity: 'కాస్మిక్ గుర్తింపు',
      vedic: 'వేద జ్ఞానం',
      lifepath: 'జీవితం & లక్ష్యం',
      connections: 'ప్రేమ & అనుబంధాలు',
      spiritual: 'ఆత్మ & ఆధ్యాత్మికం',
      remedies: 'పరిష్కారాలు'
    },
    tools: { 
      zodiac: 'రాశిచక్రం గుర్తింపు', 
      moon: 'చంద్ర దశల ట్రాకర్', 
      numerology: 'సంఖ్యాశాస్త్రం', 
      compatibility: 'హోరల్ అనుకూలత',
      mangal: 'మంగళ దోషం',
      lucky: 'అదృష్ట ప్రొఫైల్',
      kundli: 'కుండలి చార్ట్',
      daily: 'రోజువారీ జాతకం',
      sadesati: 'శని ప్రభావం',
      chinese: 'చైనీస్ జాతకం',
      ascendant: 'లగ్నం',
      career: 'కెరీర్ మార్గం',
      finance: 'సంపద & ఆర్థికం',
      health: 'ఆరోగ్యం',
      relationship_karma: 'సంబంధ కర్మ',
      tarot: 'టారో కార్డు',
      aura: 'ఆరా రంగు',
      chakra: 'చక్రాల అమరిక',
      pastlife: 'గత జన్మ',
      spiritanimal: 'ఆధ్యాత్మిక జంతువు',
      nakshatra: 'నక్షత్రం',
      gemstone: 'రత్న సూచనలు',
      ritual: 'ఆధ్యాత్మిక ఆచారాలు',
      dasha: 'గ్రహ దశలు',
      ayurveda: 'ఆయుర్వేద దోషం',
      travel: 'ప్రయాణ జాతకం',
      dream: 'కలల విశ్లేషణ',
      name_numerology: 'పేరు ప్రభావం',
      love_language: 'ప్రేమ భాష',
      shadow_self: 'షాడో సెల్ఫ్',
      elements: 'పంచభూతాల సమతుల్యత',
      vertex: 'విధి ద్వారం',
      fortune: 'అదృష్ట భాగం',
      ask_gemini: 'జెమినిని అడగండి (ఉచితం)',
      planetary_hours: 'గ్రహ గడియలు'
    },
    toolDescriptions: {
      zodiac: 'మీ వ్యక్తిత్వం మరియు భావోద్వేగాల కాస్మిక్ బ్లూప్రింట్‌ను విశ్లేషించండి.',
      moon: 'మీ మానసిక స్థితిని చంద్రుని దశలతో సమన్వయం చేసుకోండి.',
      numerology: 'మీ పుట్టిన తేదీలోని సంఖ్యా ప్రకంపనల ద్వారా మీ విధిని తెలుసుకోండి.',
      compatibility: 'ఇద్దరి జాతకాలను విశ్లేషించి మీ బంధంలోని సామరస్యాన్ని అంచనా వేయండి.',
      kundli: 'మీ పుట్టిన సమయం ఆధారంగా ఖచ్చితమైన వేద జాతక చక్రాన్ని రూపొందించండి.',
      lucky: 'గ్రహాల బలాన్ని బట్టి మీ అదృష్ట రంగులు మరియు సంఖ్యలను గుర్తించండి.',
      daily: 'కెరీర్, ఆరోగ్యం మరియు ప్రేమ కోసం రోజువారీ ఖచ్చితమైన అంచనాలు పొందండి.',
      mangal: 'కుజ దోషం ప్రభావాన్ని మరియు దానికి తగిన పరిహారాలను విశ్లేషించండి.',
      sadesati: 'శని దేవుని ప్రభావం మరియు ప్రస్తుత పరీక్షల గురించి అవగాహన పొందండి.',
      chinese: 'చైనీస్ క్యాలెండర్ ప్రకారం మీ జంతు చిహ్నం మరియు మూలకాన్ని తెలుసుకోండి.',
      ascendant: 'మీ శారీరక శక్తిని మరియు ప్రపంచాన్ని చూసే విధానాన్ని లగ్నం ద్వారా గ్రహించండి.',
      career: 'మీ కెరీర్ అభివృద్ధికి ఉత్తమమైన వృత్తి మార్గాన్ని అన్వేషించండి.',
      finance: 'గ్రహాల స్థితి ఆధారంగా మీ ఆర్థిక భద్రతను మరియు సంపదను మెరుగుపరుచుకోండి.',
      health: 'శారీరక మరియు ఆధ్యాత్మిక ఆరోగ్యం కోసం మీ మూలకాల సమతుల్యతను తనిఖీ చేయండి.',
      relationship_karma: 'మీ భాగస్వామ్య బంధాల్లోని గత జన్మ కర్మ ఫలితాలను విశ్లేషించండి.',
      tarot: 'ఈ రోజు మీకు గ్రహాలు ఇచ్చే సంకేతాలను టారో కార్డు ద్వారా తెలుసుకోండి.',
      aura: 'గ్రహాల గోచారం ఆధారంగా మీ చుట్టూ ఉన్న ఆరా రంగును విశ్లేషించండి.',
      chakra: 'మీ కాస్మిక్ సంతకం ద్వారా మీ శరీరంలోని శక్తి కేంద్రాల అమరికను తెలుసుకోండి.',
      pastlife: 'గత జన్మల జ్ఞాపకాలు మరియు ఆత్మ యొక్క ప్రయాణాన్ని విశ్లేషించండి.',
      spiritanimal: 'మీ సహజ ప్రవృత్తిని ప్రతిబింబించే ఆధ్యాత్మిక జంతువును కనుగొనండి.',
      nakshatra: 'మీ గుణగణాలలోని సూక్ష్మ భేదాలను మీ జన్మ నక్షత్రం ద్వారా తెలుసుకోండి.',
      gemstone: 'గ్రహాల బలాన్ని పెంచుకోవడానికి వ్యక్తిగత రత్న సూచనలను పొందండి.',
      ritual: 'మీ గ్రహాల స్థితికి అనుగుణంగా ప్రత్యేక ఆధ్యాత్మిక ఆచారాలను తెలుసుకోండి.',
      dasha: 'మీ జీవితంలో వచ్చే వివిధ గ్రహాల దశలను మరియు వాటి ఫలితాలను విశ్లేషించండి.',
      ayurveda: 'మీ పుట్టిన మూలకాల ఆధారంగా మీ ఆయుర్వేద దోషాన్ని (వాత, పిత్త, కఫ) నిర్ణయించండి.',
      travel: 'ప్రయాణాలకు మరియు ముఖ్యమైన పనులకు శుభ సమయాలను కనుగొనండి.',
      dream: 'మీ కలల వెనుక ఉన్న రహస్యాలను జ్యోతిష్య కోణంలో విశ్లేషించండి.',
      name_numerology: 'మీ పేరు మీ జీవిత గమనంపై చూపే ప్రభావాన్ని విశ్లేషించండి.',
      love_language: 'మీ ప్రేమను వ్యక్తం చేసే మరియు స్వీకరించే విధానాన్ని గ్రహాల ద్వారా తెలుసుకోండి.',
      shadow_self: 'మీ వ్యక్తిత్వంలోని రహస్య కోణాలను అన్వేషించి సంపూర్ణతను సాధించండి.',
      elements: 'మీ జాతకంలో పంచభూతాల పంపిణీని మరియు వాటి ప్రభావాన్ని లెక్కించండి.',
      vertex: 'మీ జీవితంలో ఎదురయ్యే విధి నిర్ణయాలను మరియు ముఖ్యమైన వ్యక్తులను గుర్తించండి.',
      fortune: 'మీ జీవితంలో అదృష్టం మరియు ఆనందం సహజంగా ఎక్కడ లభిస్తాయో తెలుసుకోండి.',
      ask_gemini: 'మా మాస్టర్ ఇంటెలిజెన్స్‌ను ఏదైనా ఆధ్యాత్మిక ప్రశ్న అడగండి.',
      planetary_hours: 'ఏ పనులు ఎప్పుడు చేయాలో నిర్ణయించుకోవడానికి గ్రహ గడియలను ఉపయోగించండి.'
    },
    labels: { 
      name: 'పూర్తి పేరు', 
      pronouns: 'సర్వనామాలు',
      dob: 'పుట్టిన తేదీ', 
      tob: 'పుట్టిన సమయం', 
      loc: 'పుట్టిన స్థలం', 
      submit: 'అంచనా వేయండి',
      westernSign: 'పాశ్చాత్య సూర్య రాశి',
      vedicSign: 'వేద రాశి',
      searchTools: 'సాధనాలను వెతకండి...',
      backToHub: 'హబ్‌కి తిరిగి వెళ్ళు',
      moduleCode: 'మాడ్యూల్ కోడ్',
      inquiryDetails: 'విచారణ వివరాలు',
      systemStandby: 'సిస్టమ్ స్టాండ్‌బై',
      initializeDataDesc: 'నిర్దిష్ట మాడ్యూల్ ఫీడ్‌బ్యాక్ పొందడానికి పుట్టిన వివరాలను నమోదు చేయండి.',
      dayPlaceholder: 'తేదీ',
      monthPlaceholder: 'నెల',
      yearPlaceholder: 'సంవత్సరం',
      pronounOptions: ['అతను/అతని', 'ఆమె/ఆమెది', 'వారు/వారి', 'చెప్పడానికి ఇష్టపడను']
    },
    results: {
      profile: 'కాస్మిక్ ప్రొఫైల్',
      status: 'స్థితి',
      phase: 'దశ',
      rising: 'లగ్నం',
      sun: 'రాశి',
      focus: 'లక్ష్యం',
      forecast: 'అంచనా',
      moonPhase: 'చంద్ర దశ',
      in: 'లో'
    }
  },
  hi: {
    nav: { home: 'प्रीमियम होम', about: 'बारे में', tools: 'प्रोफेशनल हब', blog: 'क्रॉनिकल्स', contact: 'संपर्क', admin: 'एडमिन' },
    hero: { title: 'एस्ट्रो विजन AI के साथ अपने भाग्य की खोज करें', subtitle: '5 भाषाओं में उन्नत AI-संचालित ज्योतिष अंतर्दृष्टि।' },
    contact: {
      title: 'ब्रह्मांडीय सहायता से संपर्क करें',
      subtitle: 'संपर्क करें',
      desc: 'क्या आपके पास अपनी रिपोर्ट या ग्रहों के बारे में प्रश्न हैं? हमारे मार्गदर्शक आपकी यात्रा में सहायता के लिए यहाँ हैं।',
      nameLabel: 'आपका नाम',
      namePlaceholder: 'पूरा नाम',
      emailLabel: 'ईमेल पता',
      emailPlaceholder: 'email@address.com',
      messageLabel: 'हम आपकी क्या मदद कर सकते हैं?',
      messagePlaceholder: 'अपनी पूछताछ का वर्णन करें...',
      button: 'संदेश भेजें',
      officeTitle: 'वैश्विक उपस्थिति',
      officeAddr: 'कार्यालय मुख्यालय',
      officeAddrDetail: '123 एस्ट्रल लेन, स्टारी हाइट्स, मुंबई, भारत',
      socialTitle: 'हमारी यात्रा का अनुसरण करें'
    },
    categories: {
      identity: 'ब्रह्मांडीय पहचान',
      vedic: 'वैदिक ज्ञान',
      lifepath: 'जीवन और उद्देश्य',
      connections: 'प्रेम और संबंध',
      spiritual: 'आत्मा और आध्यात्मिकता',
      remedies: 'उपाय और भाग्य'
    },
    tools: { 
      zodiac: 'राशि चक्र खोजक', 
      moon: 'चंद्र चरण ट्रैकर', 
      numerology: 'अंक ज्योतिष', 
      compatibility: 'अनुकूलता जाँचकर्ता',
      mangal: 'मंगल दोष जाँच',
      lucky: 'लकी प्रोफाइल',
      kundli: 'कुण्डली चार्ट',
      daily: 'दैनिक राशिफल',
      sadesati: 'साढ़े साती',
      chinese: 'चीनी राशिफल',
      ascendant: 'लग्न',
      career: 'करियर पथ',
      finance: 'धन और वित्त',
      health: 'स्वास्थ्य',
      relationship_karma: 'संबंध कर्म',
      tarot: 'दैनिक टैरो',
      aura: 'आभामंडल विश्लेषण',
      chakra: 'चक्र संतुलन',
      pastlife: 'पूर्व जन्म',
      spiritanimal: 'आत्मा पशु',
      nakshatra: 'नक्षत्र खोजक',
      gemstone: 'रत्न सुझाव',
      ritual: 'व्यक्तिगत अनुष्ठान',
      dasha: 'ग्रह दशा',
      ayurveda: 'आयुर्वेदिक दोष',
      travel: 'यात्रा पूर्वानुमान',
      dream: 'स्वप्न विश्लेषण',
      name_numerology: 'नाम कंपन',
      love_language: 'प्रेम भाषा',
      shadow_self: 'छाया स्वयं',
      elements: 'तत्व संतुलन',
      vertex: 'भाग्य द्वार',
      fortune: 'भाग्य का हिस्सा',
      ask_gemini: 'जेमिनी से पूछें (मुक्त प्रश्न)',
      planetary_hours: 'ग्रहों की होरा'
    },
    toolDescriptions: {
      zodiac: 'अपने अहंकार, भावनाओं और बाहरी व्यक्तित्व के मौलिक खाके को समझें।',
      moon: 'अपनी भावनात्मक लय को चंद्र चक्रों के साथ जोड़ें।',
      numerology: 'अपने भाग्य की कंपन आवृत्ति को उजागर करने के लिए अपने जीवन पथ संख्या की गणना करें।',
      compatibility: 'अपने संघ की ऊर्जावान सद्भाव और कर्म चुनौतियों का मूल्यांकन करने के लिए दो जन्म चार्ट का विश्लेषण करें।',
      kundli: 'अपने जन्म के सटीक क्षण पर ग्रहों की स्थिति का एक व्यापक वैदिक विवरण प्राप्त करें।',
      lucky: 'ग्रहों की शक्ति के आधार पर अपने शुभ रंग, संख्या और रत्न की पहचान करें।',
      daily: 'करियर, स्वास्थ्य और पारस्परिक संबंधों के लिए उच्च-सटीक पूर्वानुमान प्राप्त करें।',
      mangal: 'ऊर्जावान असंतुलन की पहचान करने और सुधारात्मक उपायों का सुझाव देने के लिए मंगल की स्थिति का विश्लेषण करें।',
      sadesati: 'वर्तमान जीवन परीक्षणों को समझने के लिए अपने जन्म के चंद्रमा के सापेक्ष शनि के गोचर की गणना करें।',
      chinese: 'चंद्र कैलेंडर के आधार पर अपने पशु चिन्ह और तात्विक संबंध की खोज करें।',
      ascendant: 'अपनी शारीरिक जीवन शक्ति और तत्काल विश्व-दृष्टि को समझने के लिए अपना लग्न निर्धारित करें।',
      career: 'अपने इष्टतम व्यावसायिक पथ की पहचान करने के लिए दशम भाव और मिडहेवन का विश्लेषण करें।',
      finance: 'अपनी भौतिक प्रचुरता और वित्तीय सुरक्षा को अनुकूलित करने के लिए ग्रहों के धन संकेतकों का मूल्यांकन करें।',
      health: 'शारीरिक और आध्यात्मिक जीवन शक्ति बनाए रखने के लिए छठे भाव और तत्व संतुलन का आकलन करें।',
      relationship_karma: 'अपनी महत्वपूर्ण साझेदारियों के भीतर पिछले जन्म की गूँज और कर्म पैटर्न की जाँच करें।',
      tarot: 'वर्तमान चक्र के लिए प्रतीकात्मक मार्गदर्शन प्राप्त करने के लिए एक कार्ड चुनें।',
      aura: 'ग्रहों के गोचर के आधार पर अपने शरीर के चारों ओर विद्युत चुंबकीय क्षेत्र की कल्पना करें।',
      chakra: 'अपने कॉस्मिक हस्ताक्षर के माध्यम से ऊर्जा अवरोधों और संतुलन के अवसरों की पहचान करें।',
      pastlife: 'पिछले जन्मों से संबंधित गहरी अवचेतन स्मृतियों और आत्मा के विषयों तक पहुँचें।',
      spiritanimal: 'अपनी मौलिक ऊर्जावान प्रतिध्वनि के आधार पर अपने दिव्य पशु मार्गदर्शक की पहचान करें।',
      nakshatra: 'अपने चरित्र की सूक्ष्म बारीकियों को उजागर करने के लिए अपना विशिष्ट नक्षत्र खोजें।',
      gemstone: 'ग्रहों की शक्ति बढ़ाने के लिए उपचारात्मक पत्थरों की व्यक्तिगत सिफारिशें प्राप्त करें।',
      ritual: 'अपने वर्तमान ज्योतिषीय गोचर के अनुरूप विशेष आध्यात्मिक प्रथाओं की खोज करें।',
      dasha: 'अपने जीवन चक्र को संचालित करने वाली ग्रहों की अवधियों के कालानुक्रमिक अनुक्रम का विश्लेषण करें।',
      ayurveda: 'अपने जन्मजात तत्व संतुलन के आधार पर अपना आयुर्वेदिक दोष (वात, पित्त, कफ) निर्धारित करें।',
      travel: 'अपनी यात्राओं के लिए सबसे शुभ समय और दिशाएँ खोजने के लिए सितारों से परामर्श करें।',
      dream: 'ज्योतिषीय दृष्टिकोण से अपने अवचेतन की प्रतीकात्मक भाषा की व्याख्या करें।',
      name_numerology: 'अपने जीवन की यात्रा पर अपने नाम के कंपन प्रभाव का विश्लेषण करें।',
      love_language: 'शुक्र और मंगल के आधार पर स्नेह देने और प्राप्त करने की अपनी कॉस्मिक शैली की खोज करें।',
      shadow_self: 'गहरे आत्म-एकीकरण के लिए अपने व्यक्तित्व के छिपे हुए पहलुओं का अन्वेषण करें।',
      elements: 'अपने जन्म के चार्ट में अग्नि, पृथ्वी, वायु और जल के वितरण की गणना करें।',
      vertex: 'इस गणितीय शक्ति बिंदु के माध्यम से अपने भाग्य द्वार और पूर्व-निर्धारित मुलाकातों की पहचान करें।',
      fortune: 'यह जानने के लिए कि सांसारिक सफलता और आनंद स्वाभाविक रूप से कहाँ प्रवाहित होते हैं, अपना भाग्य बिंदु खोजें।',
      ask_gemini: 'गहरे विश्लेषण के लिए हमारी मास्टर इंटेलिजेंस से तत्वमीमांसा संबंधी प्रश्न पूछें।',
      planetary_hours: 'विशिष्ट कार्यों के लिए अपने समय को अनुकूलित करने के लिए प्रत्येक घंटे के शासक ग्रह की गणना करें।'
    },
    labels: { 
      name: 'पूरा नाम', 
      pronouns: 'सर्वनाम',
      dob: 'जन्म तिथि', 
      tob: 'जन्म का समय', 
      loc: 'जन्म स्थान', 
      submit: 'अंतर्दृष्टि प्राप्त करें',
      westernSign: 'पश्चिमी सूर्य राशि',
      vedicSign: 'वैदिक राशि',
      searchTools: 'उपकरण खोजें...',
      backToHub: 'हब पर वापस जाएं',
      moduleCode: 'मॉड्यूल कोड',
      inquiryDetails: 'पूछताछ विवरण',
      systemStandby: 'सिस्टम स्टैंडबाय',
      initializeDataDesc: 'विशिष्ट मॉड्यूल प्रतिक्रिया प्राप्त करने के लिए जन्म विवरण दर्ज करें।',
      dayPlaceholder: 'दिन',
      monthPlaceholder: 'महीना',
      yearPlaceholder: 'वर्ष',
      pronounOptions: ['वह (पु.)', 'वह (स्त्री.)', 'वे/उन्हें', 'बताना नहीं चाहता/चाहती']
    },
    results: {
      profile: 'कॉस्मिक प्रोफाइल',
      status: 'स्थिति',
      phase: 'चरण',
      rising: 'लग्न',
      sun: 'राशि',
      focus: 'केंद्रित',
      forecast: 'पूर्वानुमान',
      moonPhase: 'चंद्र चरण',
      in: 'में'
    }
  },
  ta: {
    nav: { home: 'பிரீமியம் முகப்பு', about: 'பற்றி', tools: 'புரொபஷனல் ஹப்', blog: 'குரோனிகல்ஸ்', contact: 'தொடர்பு', admin: 'நிர்வாகி' },
    hero: { title: 'ஆஸ்ட்ரோ விஷன் AI உடன் உங்கள் விதியை கண்டறியவும்', subtitle: '5 மொழிகளில் மேம்பட்ட AI-இயங்கும் ஜோதிட நுண்ணறிவு.' },
    contact: {
      title: 'பிரபஞ்ச உதவியைத் தொடர்பு கொள்ளவும்',
      subtitle: 'எங்களைத் தொடர்பு கொள்ளுங்கள்',
      desc: 'உங்கள் அறிக்கைகள் அல்லது கிரக நிலைகள் பற்றி ஏதேனும் கேள்விகள் உள்ளதா? మీకు సహాయం చేయడానికి మా గைడ్‌లు సిద్ధంగా ఉన్నారు.',
      nameLabel: 'உங்கள் பெயர்',
      namePlaceholder: 'முழு பெயர்',
      emailLabel: 'மின்னஞ்சல் முகவரி',
      emailPlaceholder: 'email@address.com',
      messageLabel: 'நாங்கள் உங்களுக்கு ఎలా உதவ முடியும்?',
      messagePlaceholder: 'உங்கள் விசாரணையை விளக்கவும்...',
      button: 'செய்தி அனுப்பு',
      officeTitle: 'உலகளாவிய இருப்பு',
      officeAddr: 'தலைமை அலுவலகம்',
      officeAddrDetail: '123 ஆஸ்ட்ரல் லேன், ஸ்டாரி ஹைட்ஸ், மும்பை, இந்தியா',
      socialTitle: 'எமது பயணத்தைப் பின்தொடரவும்'
    },
    categories: {
      identity: 'பிரபஞ்ச அடையாளம்',
      vedic: 'வேத ஞானம்',
      lifepath: 'வாழ்க்கை & நோக்கம்',
      connections: 'காதல் & உறவுகள்',
      spiritual: 'ஆன்மா & ஆன்மீகம்',
      remedies: 'பரிகாரங்கள்'
    },
    tools: { 
      zodiac: 'இராசி கண்டுபிடிப்பான்', 
      moon: 'சந்திர நிலை கண்காணிப்பு', 
      numerology: 'எண் கணிதம்', 
      compatibility: 'பொருத்தம்',
      mangal: 'செவ்வாய் தோஷம்',
      lucky: 'அதிர்ஷ்ட சுயவிவரம்',
      kundli: 'ஜாதக கட்டம்',
      daily: 'தினசரி ராசிபலன்',
      sadesati: 'ஏழரை சனி',
      chinese: 'சீன ராசி',
      ascendant: 'லக்னம்',
      career: 'தொழில் பாதை',
      finance: 'செல்வம் & நிதி',
      health: 'ஆரோக்கியம்',
      relationship_karma: 'உறவு கர்மா',
      tarot: 'தினசரி டாரோட்',
      aura: 'ஆரா வண்ணம்',
      chakra: 'சக்கர சீரமைப்பு',
      pastlife: 'முந்தைய ஜென்மம்',
      spiritanimal: 'ஆன்மீக விலங்கு',
      nakshatra: 'நட்சத்திரம்',
      gemstone: 'ராசி கற்கள்',
      ritual: 'ஆன்மீக சடங்குகள்',
      dasha: 'திசை பலன்கள்',
      ayurveda: 'ஆயுர்வேத தோஷம்',
      travel: 'பயண முன்னறிவிப்பு',
      dream: 'கனவு விளக்கம்',
      name_numerology: 'பெயர் அதிர்வு',
      love_language: 'காதல் மொழி',
      shadow_self: 'நிழல் சுயவிவரம்',
      elements: 'பஞ்சபூத సమநிலை',
      vertex: 'விதி வாசல்',
      fortune: 'அதிர்ஷ்ட பாகம்',
      ask_gemini: 'ஜெமினியிடம் கேளுங்கள் (இலவச கேள்வி)',
      planetary_hours: 'கோள் நேரங்கள்'
    },
    toolDescriptions: {
      zodiac: 'உங்கள் ஈகோ, உணர்ச்சிகள் மற்றும் ஆளுமையின் அடிப்படை வரைபடத்தை பகுப்பாய்வு செய்யுங்கள்.',
      moon: 'சந்திர சுழற்சிகளுடன் உங்கள் உணர்ச்சித் திறனை ஒருங்கிணைக்கவும்.',
      numerology: 'உங்கள் விதி எண்ணின் அதிர்வு அதிர்வெண்ணைக் கணக்கிடுங்கள்.',
      compatibility: 'இரு ஜாதகங்களை ஒப்பிட்டு உறவின் இணக்கத்தை மதிப்பிடுங்கள்.',
      kundli: 'பிறந்த நேரத்தின் அடிப்படையில் துல்லியமான வேத ஜாதகத்தை உருவாக்குங்கள்.',
      lucky: 'கிரக நிலைகளின் அடிப்படையில் உங்கள் அதிர்ஷ்ட நிறங்கள் மற்றும் எண்களைக் கண்டறியவும்.',
      daily: 'தொழில், ஆரோக்கியம் மற்றும் உறவுகளுக்கான தினசரி துல்லியமான கணிப்புகளைப் பெறுங்கள்.',
      mangal: 'செவ்வாய் தோஷத்தின் தாக்கம் மற்றும் அதற்கான பரிகாரங்களை பகுப்பாய்வு செய்யுங்கள்.',
      sadesati: 'சனி கிரகத்தின் தாக்கம் மற்றும் தற்போதைய சோதனைகளைப் புரிந்து கொள்ளுங்கள்.',
      chinese: 'சீன நாட்காட்டியின் அடிப்படையில் உங்கள் விலங்கு அடையாளம் மற்றும் பஞ்சபூதத்தை அறியுங்கள்.',
      ascendant: 'உலகைப் பார்க்கும் உங்கள் பார்வையை லக்னத்தின் மூலம் கண்டறியுங்கள்.',
      career: 'உங்களுக்கான சிறந்த தொழில் பாதையை 10-ஆம் இடத்தைக் கொண்டு கண்டறியுங்கள்.',
      finance: 'நிதி நிலையை மேம்படுத்த கிரகங்களின் செல்வக் குறியீடுகளை மதிப்பீடு செய்யுங்கள்.',
      health: 'ஆரோக்கியமான வாழ்வுக்கு கிரகங்களின் பஞ்சபூத சமநிலையைச் சரிபார்க்கவும்.',
      relationship_karma: 'உறவுகளில் உள்ள கர்மா மற்றும் முந்தைய ஜென்மத் தொடர்புகளை ஆராயுங்கள்.',
      tarot: 'இன்றைய நாளுக்கான பிரபஞ்ச வழிகாட்டலை டாரோட் அட்டை மூலம் பெறுங்கள்.',
      aura: 'கிரகப் பெயர்ச்சிகளின் அடிப்படையில் உங்களைச் சுற்றியுள்ள ஆரா நிறத்தை அறியுங்கள்.',
      chakra: 'சக்கரங்களின் சீரமைப்பை ஜாதகத்தின் மூலம் கண்டறியுங்கள்.',
      pastlife: 'ஆன்மாவின் முந்தைய பயணங்கள் மற்றும் கர்மாவைப் பற்றி அறியுங்கள்.',
      spiritanimal: 'உங்களை வழிநடத்தும் ஆன்மீக விலங்கைக் கண்டறியுங்கள்.',
      nakshatra: 'நட்சத்திரத்தின் மூலம் உங்கள் குணாதிசயங்களின் நுணுக்கங்களை அறியுங்கள்.',
      gemstone: 'கிரகங்களின் பலத்தை அதிகரிக்க பொருத்தமான ராசி கற்களைப் பரிந்துரைக்கிறோம்.',
      ritual: 'கிரகப் பெயர்ச்சிகளுக்கு ஏற்ற ஆன்மீகச் சடங்குகளைக் கண்டறியுங்கள்.',
      dasha: 'வாழ்க்கைச் சுழற்சியை ஆளும் தசா புத்திகளைப் பகுப்பாய்வு செய்யுங்கள்.',
      ayurveda: 'பிறப்பு ஜாதகத்தின் மூலம் உங்கள் ஆயுர்வேத தோஷத்தைத் தீர்மானியுங்கள்.',
      travel: 'பயணங்களுக்கு உகந்த நேரத்தையும் திசையையும் கண்டறியுங்கள்.',
      dream: 'கனவுகளின் மறைமுகப் பொருளை ஜோதிட ரீதியாக விளக்குகிறோம்.',
      name_numerology: 'பெயர் உங்கள் வாழ்க்கையில் ஏற்படுத்தும் அதிர்வுத் தாக்கத்தைப் பகுப்பாய்வு செய்யுங்கள்.',
      love_language: 'சுக்கிரன் மற்றும் செவ்வாயின் அடிப்படையில் உங்கள் காதல் மொழியை அறியுங்கள்.',
      shadow_self: 'உங்கள் ஆளுமையின் மறைக்கப்பட்ட பக்கங்களை ஆராய்ந்து முழுமையை அடையுங்கள்.',
      elements: 'ஜாதகத்தில் உள்ள பஞ்சபூதங்களின் பங்கீட்டைக் கணக்கிடுங்கள்.',
      vertex: 'விதி தீர்மானிக்கும் சந்திப்புகள் மற்றும் நிகழ்வுகளைக் கண்டறியுங்கள்.',
      fortune: 'அதிர்ஷ்டம் மற்றும் மகிழ்ச்சி எங்குள்ளது என்பதைக் கண்டறியுங்கள்.',
      ask_gemini: 'ஆழ்ந்த நுண்ணறிவுகளுக்கு எமது AI-யிடம் கேள்விகளைக் கேளுங்கள்.',
      planetary_hours: 'முக்கியமான செயல்களைச் செய்ய கிரக நேரங்களைக் கணக்கிடுங்கள்.'
    },
    labels: { 
      name: 'முழு பெயர்', 
      pronouns: 'பிரதிபெயர்கள்',
      dob: 'பிறந்த தேதி', 
      tob: 'பிறந்த நேரம்', 
      loc: 'பிறந்த இடம்', 
      submit: 'கணக்கிடுங்கள்',
      westernSign: 'மேற்கத்திய ராசி',
      vedicSign: 'வேத రాశి',
      searchTools: 'கருவிகளைத் தேடுங்கள்...',
      backToHub: 'ஹப்‌கி తిరిగి వెళ్ళు',
      moduleCode: 'தொகுதி குறியீடு',
      inquiryDetails: 'விசாரணை விவரங்கள்',
      systemStandby: 'அமைப்பு காத்திருப்பு',
      initializeDataDesc: 'குறிப்பிட்ட தொகுதி கருத்தைப் பெற பிறந்த விவரங்களை உள்ளிடவும்.',
      dayPlaceholder: 'తేదీ',
      monthPlaceholder: 'மாதம்',
      yearPlaceholder: 'ஆண்டு',
      pronounOptions: ['அவன்/அவர்', 'அவள்/அவர்', 'அவர்கள்', 'சொல்ல விரும்பவில்லை']
    },
    results: {
      profile: 'பிரபஞ்ச சுயவிவரம்',
      status: 'நிலை',
      phase: 'கட்டம்',
      rising: 'லக்னம்',
      sun: 'ராசி',
      focus: 'கவனம்',
      forecast: 'கணிப்பு',
      moonPhase: 'சந்திர நிலை',
      in: 'இல்'
    }
  },
  kn: {
    nav: { home: 'ಪ್ರೀಮಿಯಂ ಹೋಮ್', about: 'ಬಗ್ಗೆ', tools: 'ಪ್ರೊಫೆಷನಲ್ ಹಬ್', blog: 'ಕ್ರಾನಿಕಲ್ಸ್', contact: 'ಸಂಬಂಧ', admin: 'ನಿರ್ವಾಹಕ' },
    hero: { title: 'ಆಸ್ಟ್ರೋ ವಿಷನ್ AI ನೊಂದಿಗೆ ನಿಮ್ಮ ಭವಿಷ್ಯವನ್ನು ಕಂಡುಕೊಳ್ಳಿ', subtitle: '5 ಭಾಷೆಗಳಲ್ಲಿ ಸುಧಾರಿತ AI-ಚಾಲಿತ ಜ್ಯೋತಿಷ್ಯ ಒಳನೋಟಗಳು.' },
    contact: {
      title: 'ಕಾಸ್ಮಿಕ್ ಸಪೋರ್ಟ್ ಅನ್ನು ಸಂಪರ್ಕಿಸಿ',
      subtitle: 'ಸಂಬಂಧಿಸಿ',
      desc: 'ನಿಮ್ಮ ವರದಿಗಳು ಅಥವಾ ಗ್ರಹಗಳ ಸ್ಥಿತಿಯ ಬಗ್ಗೆ ಪ್ರಶ್ನೆಗಳಿವೆಯೇ? ನಿಮಗೆ ಸಹಾಯ ಮಾಡಲು ನಮ್ಮ ಮಾರ್ಗದರ್ಶಕರು ಇಲ್ಲಿದ್ದಾರೆ.',
      nameLabel: 'ನಿಮ್ಮ ಹೆಸರು',
      namePlaceholder: 'ಪೂರ್ಣ ಹೆಸರು',
      emailLabel: 'ಇಮೇಲ್ ವಿಳಾಸ',
      emailPlaceholder: 'email@address.com',
      messageLabel: 'ನಾವು ನಿಮಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು?',
      messagePlaceholder: 'ನಿಮ್ಮ ವಿಚಾರಣೆಯನ್ನು ವಿವರಿಸಿ...',
      button: 'ಸಂದೇಶ ಕಳುಹಿಸಿ',
      officeTitle: 'ಜಾಗತಿಕ ಉಪಸ್ಥಿತಿ',
      officeAddr: 'ಕಚೇರಿ ಪ್ರಧಾನ ಕಚೇರಿ',
      officeAddrDetail: '123 ಆಸ್ಟ್ರಲ್ ಲೇನ್, ಸ್ಟಾರ್ರಿ ಹೈಟ್ಸ್, ಮುಂಬೈ, ಭಾರತ',
      socialTitle: 'ನಮ್ಮ ಪ್ರಯಾಣವನ್ನು ಅನುಸರಿಸಿ'
    },
    categories: {
      identity: 'ಕಾಸ್ಮಿಕ್ ಗುರುತು',
      vedic: 'ವೈದಿಕ ಜ್ಞಾನ',
      lifepath: 'ಜೀವನ & ಉದ್ದೇಶ',
      connections: 'ಪ್ರೀತಿ & ಸಂಬಂಧಗಳು',
      spiritual: 'ಆತ್ಮ & ಆಧ್ಯಾತ್ಮಿಕತೆ',
      remedies: 'ಪರಿಹಾರಗಳು'
    },
    tools: { 
      zodiac: 'ರಾಶಿಚಕ್ರ ಪತ್ತೆ', 
      moon: 'ಚಂದ್ರನ ಹಂತ', 
      numerology: 'ಸಂಖ್ಯಾಶಾಸ್ತ್ರ', 
      compatibility: 'ಹೊಂದಾಣಿಕೆ',
      mangal: 'ಮಂಗಳ ದೋಷ',
      lucky: 'ಅದೃಷ್ಟ ಪ್ರೊಫೈಲ್',
      kundli: 'ಕುಂಡಲಿ ಚಾರ್ಟ್',
      daily: 'ದೈನಂದಿನ ಭವಿಷ್ಯ',
      sadesati: 'ಸಾಡೆ ಸಾತಿ',
      chinese: 'ಚೈನೀಸ್ ರಾಶಿ',
      ascendant: 'ಲಗ್ನ',
      career: 'ವೃತ್ತಿ ಮಾರ್ಗ',
      finance: 'ಸಂಪತ್ತು ಮತ್ತು ಹಣಕಾಸು',
      health: 'ಆರೋಖ್ಯ',
      relationship_karma: 'ಸಂಬಂಧ ಕರ್ಮ',
      tarot: 'ದೈನಂದಿನ ಟ್ಯಾರೋ',
      aura: 'ಆಭಾಮಂಡಲ ಬಣ್ಣ',
      chakra: 'ಚಕ್ರ ಜೋಡಣೆ',
      pastlife: 'ಪೂರ್ವ ಜನ್ಮ',
      spiritanimal: 'ಆತ್ಮ ಪ್ರಾಣಿ',
      nakshatra: 'ನಕ್ಷತ್ರ',
      gemstone: 'ರತ್ನಗಳ ಶಿಫಾರಸು',
      ritual: 'ವೈಯಕ್ತಿಕ ಆಚರಣೆಗಳು',
      dasha: 'ಗ್ರಹ ದಶೆ',
      ayurveda: 'ಆಯುವೇದ ದೋಷ',
      travel: 'ಪ್ರಯಾಣ ಮುನ್ಸೂಚನೆ',
      dream: 'ಕನಸಿನ ವಿಶ್ಲೇಷಣೆ',
      name_numerology: 'ಹೆಸರಿನ ಕಂಪನ',
      love_language: 'ಪ್ರೀತಿಯ ಭಾಷೆ',
      shadow_self: 'ನೆರಳು ಸ್ವಯಂ',
      elements: 'ತತ್ವ ಸಮತೋಲನ',
      vertex: 'ವಿಧಿ ದ್ವಾರ',
      fortune: 'ಅದೃಷ್ಟದ ಭಾಗ',
      ask_gemini: 'ಜೆಮಿನಿಯನ್ನು ಕೇಳಿ (ಮುಕ್ತ ಪ್ರಶ್ನೆ)',
      planetary_hours: 'ಗ್ರಹಗಳ ಘಂಟೆಗಳು'
    },
    toolDescriptions: {
      zodiac: 'ನಿಮ್ಮ ಅಹಂಕಾರ, ಭಾವನೆಗಳು ಮತ್ತು ವ್ಯಕ್ತಿತ್ವದ ಮೂಲಭೂತ ಕಾಸ್ಮಿಕ್ ನಕ್ಷೆಯನ್ನು ವಿಶ್ಲೇಷಿಸಿ.',
      moon: 'ಚಂದ್ರನ ಚಕ್ರಗಳೊಂದಿಗೆ ನಿಮ್ಮ ಭಾವನಾತ್ಮಕ ಲಯವನ್ನು ಸಮನ್ವಯಗೊಳಿಸಿ.',
      numerology: 'ನಿಮ್ಮ ಜನ್ಮ ದಿನಾಂಕದ ಸಂಖ್ಯಾ ಕಂಪನಗಳ ಮೂಲಕ ನಿಮ್ಮ ವಿಧಿಯನ್ನು ತಿಳಿಯಿರಿ.',
      compatibility: 'ಇಬ್ಬರ ಜಾತಕಗಳನ್ನು ಹೋಲಿಸಿ ನಿಮ್ಮ ಸಂಬಂಧದ ಸಾಮರಸ್ಯವನ್ನು ಅಳೆಯಿರಿ.',
      kundli: 'ನಿಮ್ಮ ಜನ್ಮ ಸಮಯದ ಆಧಾರದ ಮೇಲೆ ನಿಖರವಾದ ವೈದಿಕ ಜಾತಕವನ್ನು ತಯಾರಿಸಿ.',
      lucky: 'ಗ್ರಹಗಳ ಬಲದ ಆಧಾರದ ಮೇಲೆ ನಿಮ್ಮ ಅದೃಷ್ಟದ ಬಣ್ಣಗಳು ಮತ್ತು ಸಂಖ್ಯೆಗಳನ್ನು ತಿಳಿಯಿರಿ.',
      daily: 'ವೃತ್ತಿ, ಆರೋಗ್ಯ ಮತ್ತು ಪ್ರೀತಿಗಾಗಿ ದೈನಂದಿನ ನಿಖರ ಮುನ್ಸೂಚನೆಗಳನ್ನು ಪಡೆಯಿರಿ.',
      mangal: 'ಮಂಗಳ ದೋಷದ ಪ್ರಭಾವ ಮತ್ತು ಅದಕ್ಕೆ ತಕ್ಕ ಪರಿಹಾರಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಿ.',
      sadesati: 'ಶನಿಯ ಪ್ರಭಾವ ಮತ್ತು ಪ್ರಸ್ತುತ ಜೀವನದ ಪರೀಕ್ಷೆಗಳ ಬಗ್ಗೆ ತಿಳಿಯಿರಿ.',
      chinese: 'ಚೈನೀಸ್ ಕ್ಯಾಲೆಂಡರ್ ಪ್ರಕಾರ ನಿಮ್ಮ ಪ್ರಾಣಿ ಚಿಹ್ನೆಯನ್ನು ತಿಳಿಯಿರಿ.',
      ascendant: 'ನಿಮ್ಮ ಶಾರೀರಿಕ ಶಕ್ತಿ ಮತ್ತು ಜಗತ್ತನ್ನು ನೋಡುವ ದೃಷ್ಟಿಕೋನವನ್ನು ಲಗ್ನದ ಮೂಲಕ ತಿಳಿಯಿರಿ.',
      career: 'ನಿಮ್ಮ ವೃತ್ತಿಜೀವನದ ಅಭಿವೃದ್ಧಿಗೆ ಸೂಕ್ತವಾದ ಮಾರ್ಗವನ್ನು ಕಂಡುಕೊಳ್ಳಿ.',
      finance: 'ನಿಮ್ಮ ಆರ್ಥಿಕ ಭದ್ರತೆಯನ್ನು ಹೆಚ್ಚಿಸಲು ಗ್ರಹಗಳ ಸೂಚಕಗಳನ್ನು ಬಳಸಿ.',
      health: 'ಶಾರೀರಿಕ ಮತ್ತು ಆಧ್ಯಾತ್ಮಿಕ ಆರೋಗ್ಯಕ್ಕಾಗಿ ಪಂಚಭೂತಗಳ ಸಮತೋಲನವನ್ನು ಪರಿಶೀಲಿಸಿ.',
      relationship_karma: 'ನಿಮ್ಮ ಸಂಬಂಧಗಳಲ್ಲಿನ ಕರ್ಮ ಫಲಗಳನ್ನು ಮತ್ತು ಹಿಂದಿನ ಜನ್ಮದ ಪ್ರಭಾವವನ್ನು ತಿಳಿಯಿರಿ.',
      tarot: 'ಇಂದಿನ ದಿವಸಕ್ಕೆ ಗ್ರಹಗಳು ನೀಡುವ ಸಂಕೇತಗಳನ್ನು ಟ್ಯಾರೋ ಕಾರ್ಡ್ ಮೂಲಕ ತಿಳಿಯಿರಿ.',
      aura: 'ನಿಮ್ಮ ಸುತ್ತಲಿನ ಆಭಾಮಂಡಲದ ಬಣ್ಣವನ್ನು ಗ್ರಹಗಳ ಸ್ಥಿತಿಗೆ ಅನುಗುಣವಾಗಿ ತಿಳಿಯಿರಿ.',
      chakra: 'ನಿಮ್ಮ ಜಾತಕದ ಮೂಲಕ ಶರೀರದ ಶಕ್ತಿ ಕೇಂದ್ರಗಳ ಜೋಡಣೆಯನ್ನು ತಿಳಿಯಿರಿ.',
      pastlife: 'ಹಿಂದಿನ ಜನ್ಮಗಳ ನೆನಪುಗಳು ಮತ್ತು ಆತ್ಮದ ಪ್ರಯಾಣವನ್ನು ವಿಶ್ಲೇಷಿಸಿ.',
      spiritanimal: 'ನಿಮ್ಮ ವ್ಯಕ್ತಿತ್ವವನ್ನು ಪ್ರತಿಬಿಂಬಿಸುವ ಆಧ್ಯಾತ್ಮಿಕ ಪ್ರಾಣಿಯನ್ನು ಕಂಡುಕೊಳ್ಳಿ.',
      nakshatra: 'ನಕ್ಷತ್ರದ ಮೂಲಕ ನಿಮ್ಮ ಗುಣಲಕ್ಷಣಗಳ ಸೂಕ್ಷ್ಮ ವಿವರಗಳನ್ನು ತಿಳಿಯಿರಿ.',
      gemstone: 'ಗ್ರಹಗಳ ಬಲ ಹೆಚ್ಚಿಸಲು ಸೂಕ್ತವಾದ ರತ್ನಗಳ ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಿರಿ.',
      ritual: 'ನಿಮ್ಮ ಪ್ರಸ್ತುತ ಗ್ರಹಗಳ ಸ್ಥಿತಿಗೆ ಅನುಗುಣವಾದ ಆಧ್ಯಾತ್ಮಿಕ ಆಚರಣೆಗಳನ್ನು ತಿಳಿಯಿರಿ.',
      dasha: 'ಜೀವನದ ವಿವಿಧ ಹಂತಗಳಲ್ಲಿ ಬರುವ ಗ್ರಹಗಳ ದಶೆಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಿ.',
      ayurveda: 'ನಿಮ್ಮ ಜನ್ಮ ಅಂಶಗಳ ಆಧಾರದ ಮೇಲೆ ಆಯುರ್ವೇದ ದೋಷವನ್ನು ತಿಳಿಯಿರಿ.',
      travel: 'ಪ್ರಯಾಣಕ್ಕೆ ಮತ್ತು ಶುಭ ಕಾರ್ಯಗಳಿಗೆ ಸೂಕ್ತ ಸಮಯವನ್ನು ಕಂಡುಕೊಳ್ಳಿ.',
      dream: 'ನಿಮ್ಮ ಕನಸುಗಳ ಹಿಂದಿನ ರಹಸ್ಯಗಳನ್ನು ಜ್ಯೋತಿಷ್ಯದ ದೃಷ್ಟಿಕೋನದಿಂದ ತಿಳಿಯಿರಿ.',
      name_numerology: 'ನಿಮ್ಮ ಹೆಸರು ನಿಮ್ಮ ಜೀವನದ ಮೇಲೆ ಬೀರುವ ಕಂಪನ ಪ್ರಭಾವವನ್ನು ವಿಶ್ಲೇಷಿಸಿ.',
      love_language: 'ನಿಮ್ಮ ಪ್ರೀತಿಯನ್ನು ವ್ಯಕ್ತಪಡಿಸುವ ಕಾಸ್ಮಿಕ್ ಶೈಲಿಯನ್ನು ತಿಳಿಯಿರಿ.',
      shadow_self: 'ನಿಮ್ಮ ವ್ಯಕ್ತಿತ್ವದ ಗುಪ್ತ ಮಗ್ಗುಲುಗಳನ್ನು ಅನ್ವೇಷಿಸಿ ಪೂರ್ಣತೆಯನ್ನು ಸಾಧಿಸಿ.',
      elements: 'ಜಾತಕದಲ್ಲಿ ಅಗ್ನಿ, ಪೃಥ್ವಿ, ವಾಯು ಮತ್ತು ಜಲ ತತ್ವಗಳ ಹಂಚಿಕೆಯನ್ನು ಲೆಕ್ಕಹಾಕಿ.',
      vertex: 'ನಿಮ್ಮ ಜೀವನದಲ್ಲಿ ಎದುರಾಗುವ ವಿಧಿ ನಿರ್ಧಾರಿತ ಭೇಟಿಗಳನ್ನು ಗುರುತಿಸಿ.',
      fortune: 'ನಿಮ್ಮ ಜೀವನದಲ್ಲಿ ಅದೃಷ್ಟ ಮತ್ತು ಸಂತೋಷ ಸಹಜವಾಗಿ ಎಲ್ಲಿದೆ ಎಂದು ತಿಳಿಯಿರಿ.',
      ask_gemini: 'ನಮ್ಮ ಮಾಸ್ಟರ್ ಇಂಟೆಲಿಜೆನ್ಸ್ ಅನ್ನು ಯಾವುದೇ ಆಧ್ಯಾತ್ಮಿಕ ಪ್ರಶ್ನೆ ಕೇಳಿ.',
      planetary_hours: 'ಪ್ರಮುಖ ಕೆಲಸಗಳನ್ನು ಮಾಡಲು ಗ್ರಹಗಳ ಘಂಟೆಗಳನ್ನು ಬಳಸಿ.'
    },
    labels: { 
      name: 'ಪೂರ್ಣ ಹೆಸರು', 
      pronouns: 'ಸರ್ವನಾಮಗಳು',
      dob: 'ಹುಟ್ಟಿದ ದಿನಾಂಕ', 
      tob: 'ಹುಟ್ಟಿದ ಸಮಯ', 
      loc: 'ಹುಟ್ಟಿದ ಸ್ಥಳ', 
      submit: 'ಲೆಕ್ಕಾಚಾರ ಮಾಡಿ',
      westernSign: 'ಪಾಶ್ಚಾತ್ಯ ರಾಶಿ',
      vedicSign: 'ವೈದಿಕ ರಾಶಿ',
      searchTools: 'ಪರಿಕರಗಳನ್ನು ಹುಡುಕಿ...',
      backToHub: 'ಹಬ್‌ಗೆ ಹಿಂತಿರುಗಿ',
      moduleCode: 'ಮಾಡ್ಯೂಲ್ ಕೋಡ್',
      inquiryDetails: 'ವಿಚಾರಣೆಯ ವಿವರಗಳು',
      systemStandby: 'ಸಿಸ್ಟಮ್ ಸ್ಟ್ಯಾಂಡ್‌ಬೈ',
      initializeDataDesc: 'ನಿರ್ದಿಷ್ಟ ಮಾಡ್ಯೂಲ್ ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ಸ್ವೀಕರಿಸಲು ಜನ್ಮ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ.',
      dayPlaceholder: 'ದಿನ',
      monthPlaceholder: 'ತಿಂಗಳು',
      yearPlaceholder: 'ವರ್ಷ',
      pronounOptions: ['ಅವನು/ಅವನ', 'ಅವಳು/ಅವಳ', 'ಅವರು', 'ಹೇಳಲು ಇಷ್ಟವಿಲ್ಲ']
    },
    results: {
      profile: 'ಕಾಸ್ಮಿಕ್ ಪ್ರೊಫೈಲ್',
      status: 'స్థితి',
      phase: 'ಹಂತ',
      rising: 'ಲಗ್ನ',
      sun: 'ರಾಶಿ',
      focus: 'ಗಮನ',
      forecast: 'ಮುನ್ಸೂಚನೆ',
      moonPhase: 'ಚಂದ್ರನ ಹಂತ',
      in: 'ನಲ್ಲಿ'
    }
  }
};

export const ZODIAC_DATA = [
  { name: 'Aries', start: '03-21', end: '04-19', stone: 'Diamond', color: 'Red', element: 'Fire' },
  { name: 'Taurus', start: '04-20', end: '05-20', stone: 'Emerald', color: 'Green', element: 'Earth' },
  { name: 'Gemini', start: '05-21', end: '06-20', stone: 'Pearl', color: 'Yellow', element: 'Air' },
  { name: 'Cancer', start: '06-21', end: '07-22', stone: 'Ruby', color: 'White', element: 'Water' },
  { name: 'Leo', start: '07-23', end: '08-22', stone: 'Peridot', color: 'Gold', element: 'Fire' },
  { name: 'Virgo', start: '08-23', end: '09-22', stone: 'Sapphire', color: 'Navy Blue', element: 'Earth' },
  { name: 'Libra', start: '09-23', end: '10-22', stone: 'Opal', color: 'Pink', element: 'Air' },
  { name: 'Scorpio', start: '10-23', end: '11-21', stone: 'Topaz', color: 'Maroon', element: 'Water' },
  { name: 'Sagittarius', start: '11-22', end: '12-21', stone: 'Turquoise', color: 'Purple', element: 'Fire' },
  { name: 'Capricorn', start: '12-22', end: '01-19', stone: 'Garnet', color: 'Black', element: 'Earth' },
  { name: 'Aquarius', start: '01-20', end: '02-18', stone: 'Amethyst', color: 'Electric Blue', element: 'Air' },
  { name: 'Pisces', start: '02-19', end: '03-20', stone: 'Aquamarine', color: 'Sea Green', element: 'Water' }
];

export const VEDIC_RASHI_DATA = [
  { name: 'Mesha', en: 'Aries', start: '04-14', end: '05-14' },
  { name: 'Vrishabha', en: 'Taurus', start: '05-15', end: '06-14' },
  { name: 'Mithuna', en: 'Gemini', start: '06-15', end: '07-14' },
  { name: 'Karka', en: 'Cancer', start: '07-15', end: '08-14' },
  { name: 'Simha', en: 'Leo', start: '08-15', end: '09-15' },
  { name: 'Kanya', en: 'Virgo', start: '09-16', end: '10-16' },
  { name: 'Tula', en: 'Libra', start: '10-17', end: '11-14' },
  { name: 'Vrishchika', en: 'Scorpio', start: '11-15', end: '12-15' },
  { name: 'Dhanu', en: 'Sagittarius', start: '12-16', end: '01-13' },
  { name: 'Makara', en: 'Capricorn', start: '01-14', end: '02-12' },
  { name: 'Kumbha', en: 'Aquarius', start: '02-13', end: '03-13' },
  { name: 'Meena', en: 'Pisces', start: '03-14', end: '04-13' }
];

export const CHINESE_ZODIAC = ["Rat", "Ox", "Tiger", "Rabbit", "Dragon", "Snake", "Horse", "Goat", "Monkey", "Rooster", "Dog", "Pig"];

export const TOOL_CATEGORIES = [
  { id: 'identity', icon: '👤', tools: ['zodiac', 'ascendant', 'chinese', 'numerology', 'aura', 'spiritanimal', 'elements'] },
  { id: 'vedic', icon: '🕉️', tools: ['kundli', 'nakshatra', 'dasha', 'mangal', 'sadesati', 'ayurveda'] },
  { id: 'lifepath', icon: '🛤️', tools: ['career', 'finance', 'health', 'shadow_self', 'fortune', 'vertex'] },
  { id: 'connections', icon: '🤝', tools: ['compatibility', 'relationship_karma', 'love_language'] },
  { id: 'spiritual', icon: '✨', tools: ['tarot', 'chakra', 'pastlife', 'ritual', 'dream', 'ask_gemini'] },
  { id: 'remedies', icon: '💎', tools: ['gemstone', 'lucky', 'travel', 'name_numerology', 'daily', 'planetary_hours'] }
];

const generateLongContent = (topic: string, length: number = 850) => {
  const intro = `Astrology has always been a beacon of light for those navigating the complexities of human existence. When we talk about ${topic}, we are delving into a profound layer of cosmic significance that influences our daily lives in ways both subtle and overt. In the modern era, the integration of technology and ancient wisdom has allowed us to understand ${topic} with unprecedented depth. This article explores the multifaceted dimensions of ${topic}, providing a comprehensive guide for both beginners and seasoned practitioners. `;
  
  const bodyParagraph = `The planetary movements associated with ${topic} are indicative of larger cycles of growth and transformation. Every alignment carries a specific vibrational frequency that resonates with our personal birth charts. For instance, when ${topic} enters a critical phase, it can trigger psychological shifts that encourage us to re-evaluate our long-term goals and immediate priorities. Astrologers have noted that those who pay close attention to the nuances of ${topic} often find themselves better equipped to handle life's inevitable challenges. It is not merely about predicting the future, but about understanding the energetic weather of the present moment. Throughout history, civilizations have looked to the stars to decode the mysteries of ${topic}, finding patterns that repeat across generations and cultures. By analyzing these patterns through the lens of modern psychology and advanced AI computation, we can derive insights that are more accurate and actionable than ever before. This synthesis of the old and new is the hallmark of the current astrological renaissance. `;
  
  const repeatedBody = bodyParagraph.repeat(6);
  const conclusion = `In conclusion, ${topic} remains a vital component of our spiritual toolkit. Whether you are looking for guidance in your career, relationships, or personal development, understanding the role of ${topic} can provide the clarity you need. As we move further into 2025, the influence of ${topic} will continue to evolve, inviting us to stay curious, stay informed, and stay aligned with our highest selves. The journey through the cosmos is a lifelong exploration, and ${topic} is one of the most important landmarks on that path. Embrace the wisdom of the stars and let ${topic} guide you toward a more fulfilled and purposeful life. `;

  return intro + repeatedBody + conclusion;
};

export const MOCK_BLOGS = [
  {
    id: '1',
    title: 'How AI is Revolutionizing Modern Astrology',
    slug: 'ai-modern-astrology',
    date: '2024-03-15',
    category: 'Technology',
    excerpt: 'Explore how deep learning models are providing more accurate planetary transits than ever before.',
    content: generateLongContent('AI in Astrology'),
    tags: ['AI', 'Astrology', 'Tech'],
    image: 'https://picsum.photos/seed/astro1/800/400'
  },
  {
    id: '2',
    title: 'Understanding Your Moon Sign in 2025',
    slug: 'moon-sign-2025',
    date: '2024-03-20',
    category: 'Zodiac',
    excerpt: 'Your sun sign is your ego, but your moon sign represents your deep emotional self.',
    content: generateLongContent('Moon Signs'),
    tags: ['Moon Sign', 'Emotional Healing'],
    image: 'https://picsum.photos/seed/astro2/800/400'
  },
  {
    id: '3',
    title: 'Mercury Retrograde: A Survival Guide for Communication',
    slug: 'mercury-retrograde-guide',
    date: '2024-04-05',
    category: 'Planetary',
    excerpt: 'Navigate the technical glitches and miscommunications of the most famous planetary transit.',
    content: generateLongContent('Mercury Retrograde'),
    tags: ['Mercury', 'Communication', 'Transits'],
    image: 'https://picsum.photos/seed/mercury/800/400'
  },
  {
    id: '4',
    title: 'The Great Saturn Return: Your Cosmic Rite of Passage',
    slug: 'saturn-return-significance',
    date: '2024-04-12',
    category: 'Planetary',
    excerpt: 'Entering your late 20s or late 50s? Discover why Saturn is demanding structural changes in your life.',
    content: generateLongContent('Saturn Return'),
    tags: ['Saturn', 'Growth', 'Karma'],
    image: 'https://picsum.photos/seed/saturn/800/400'
  },
  {
    id: '5',
    title: 'Numerology and Life Path 1: The Trailblazer',
    slug: 'life-path-1-numerology',
    date: '2024-04-18',
    category: 'Numerology',
    excerpt: 'Discover the power of independence and leadership if your life path number is 1.',
    content: generateLongContent('Life Path 1'),
    tags: ['Numerology', 'Leadership', 'Destiny'],
    image: 'https://picsum.photos/seed/num1/800/400'
  },
  {
    id: '6',
    title: 'Meditation Techniques for Each Zodiac Sign',
    slug: 'zodiac-meditation',
    date: '2024-04-25',
    category: 'Meditation',
    excerpt: 'Aries needs movement, while Pisces needs silence. Find the meditation style that fits your sign.',
    content: generateLongContent('Zodiac Meditation'),
    tags: ['Meditation', 'Mindfulness', 'Zodiac'],
    image: 'https://picsum.photos/seed/meditation/800/400'
  },
  {
    id: '7',
    title: 'Venus in Libra: Harmony in Relationships',
    slug: 'venus-libra-harmony',
    date: '2024-05-02',
    category: 'Zodiac',
    excerpt: 'How the planet of love behaves in its home sign of the scales.',
    content: generateLongContent('Venus in Libra'),
    tags: ['Love', 'Venus', 'Relationships'],
    image: 'https://picsum.photos/seed/venus/800/400'
  },
  {
    id: '8',
    title: 'The Rising Sign: Why Your Ascendant Matters Most',
    slug: 'rising-sign-ascendant',
    date: '2024-05-09',
    category: 'Zodiac',
    excerpt: 'Your Ascendant is your mask to the world and the lens through which you see reality.',
    content: generateLongContent('Ascendant Signs'),
    tags: ['Ascendant', 'Identity', 'Psychology'],
    image: 'https://picsum.photos/seed/ascendant/800/400'
  },
  {
    id: '9',
    title: 'Pluto in Aquarius: The Dawn of a Digital Renaissance',
    slug: 'pluto-aquarius-digital',
    date: '2024-05-16',
    category: 'Technology',
    excerpt: 'The slow-moving planet of transformation enters the sign of technology for the next 20 years.',
    content: generateLongContent('Pluto in Aquarius'),
    tags: ['Pluto', 'Transformation', 'Society'],
    image: 'https://picsum.photos/seed/pluto/800/400'
  },
  {
    id: '10',
    title: 'Vedic vs Western Astrology: Which System is Best?',
    slug: 'vedic-western-comparison',
    date: '2024-05-23',
    category: 'Technology',
    excerpt: 'Comparing the Tropical and Sidereal zodiac systems and their unique strengths.',
    content: generateLongContent('Astrological Systems'),
    tags: ['Vedic', 'Western', 'History'],
    image: 'https://picsum.photos/seed/comparison/800/400'
  },
  {
    id: '11',
    title: 'Mars Retrograde: Managing Your Inner Fire',
    slug: 'mars-retrograde-vitality',
    date: '2024-05-30',
    category: 'Planetary',
    excerpt: 'When the planet of action slows down, how can we avoid burnout and frustration?',
    content: generateLongContent('Mars Retrograde'),
    tags: ['Mars', 'Energy', 'Action'],
    image: 'https://picsum.photos/seed/mars/800/400'
  },
  {
    id: '12',
    title: 'The Secret Power of Master Number 11',
    slug: 'master-number-11-insight',
    date: '2024-06-06',
    category: 'Numerology',
    excerpt: 'Unlocking the intuitive and visionary potential of the first Master Number.',
    content: generateLongContent('Master Number 11'),
    tags: ['Numerology', 'Intuition', 'Vibration'],
    image: 'https://picsum.photos/seed/num11/800/400'
  },
  {
    id: '13',
    title: 'Lunar Cycles and Their Effect on Sleep',
    slug: 'lunar-cycles-sleep',
    date: '2024-06-13',
    category: 'Planetary',
    excerpt: 'Scientific and spiritual perspectives on why we sleep differently during a Full Moon.',
    content: generateLongContent('Lunar Cycles'),
    tags: ['Moon', 'Sleep', 'Health'],
    image: 'https://picsum.photos/seed/sleep/800/400'
  },
  {
    id: '14',
    title: 'Chiron: The Wounded Healer in Your Chart',
    slug: 'chiron-wounded-healer',
    date: '2024-06-20',
    category: 'Planetary',
    excerpt: 'Discovering where your greatest pain becomes your greatest spiritual gift.',
    content: generateLongContent('Chiron'),
    tags: ['Healing', 'Psychology', 'Chiron'],
    image: 'https://picsum.photos/seed/chiron/800/400'
  },
  {
    id: '15',
    title: 'North Node Destiny: Finding Your Life Purpose',
    slug: 'north-node-destiny',
    date: '2024-06-27',
    category: 'Zodiac',
    excerpt: 'Your North Node points to the lessons your soul came here to learn.',
    content: generateLongContent('North Node'),
    tags: ['Destiny', 'Soul', 'Nodes'],
    image: 'https://picsum.photos/seed/northnode/800/400'
  },
  {
    id: '16',
    title: 'Jupiter in Gemini: A Year of Infinite Curiosity',
    slug: 'jupiter-gemini-transit',
    date: '2024-07-04',
    category: 'Planetary',
    excerpt: 'The planet of expansion enters the sign of communication. What it means for you.',
    content: generateLongContent('Jupiter in Gemini'),
    tags: ['Jupiter', 'Abundance', 'Gemini'],
    image: 'https://picsum.photos/seed/jupiter/800/400'
  },
  {
    id: '17',
    title: 'Fixed Stars and Global Events',
    slug: 'fixed-stars-events',
    date: '2024-07-11',
    category: 'Planetary',
    excerpt: 'Analyzing the influence of Regulus, Antares, and Sirius on historical shifts.',
    content: generateLongContent('Fixed Stars'),
    tags: ['Fixed Stars', 'Mundane Astrology', 'History'],
    image: 'https://picsum.photos/seed/stars/800/400'
  },
  {
    id: '18',
    title: 'Crystal Healing and Planetary Magic',
    slug: 'crystal-healing-planets',
    date: '2024-07-18',
    category: 'Meditation',
    excerpt: 'Pairing specific gemstones with planetary hours for ritual and manifestation.',
    content: generateLongContent('Crystals'),
    tags: ['Crystals', 'Ritual', 'Manifestation'],
    image: 'https://picsum.photos/seed/crystals/800/400'
  },
  {
    id: '19',
    title: 'The Midheaven: Decoding Your Public Legacy',
    slug: 'midheaven-career-legacy',
    date: '2024-07-25',
    category: 'Zodiac',
    excerpt: 'How the highest point in your chart determines your career and reputation.',
    content: generateLongContent('Midheaven MC'),
    tags: ['Career', 'Reputation', 'Midheaven'],
    image: 'https://picsum.photos/seed/midheaven/800/400'
  },
  {
    id: '20',
    title: 'Astrology and Ethics in the Age of AI',
    slug: 'astrology-ethics-ai',
    date: '2024-08-01',
    category: 'Technology',
    excerpt: 'Maintaining the sacred human element in automated spiritual guidance.',
    content: generateLongContent('Ethics and AI'),
    tags: ['Ethics', 'AI', 'Spirituality'],
    image: 'https://picsum.photos/seed/ethics/800/400'
  }
];
